import type { Week } from "../types";

export const week07: Week = {
  week: 7,
  title: "Operations & Supply Chain",
  tagline: "Process design, capacity, inventory, and quality — where strategy meets execution.",
  topics: ["Process flow", "Little's Law", "Inventory management", "Lean / Six Sigma"],
  lessons: [
    {
      id: "l1",
      title: "Process analysis",
      summary: "Every business is a process. Identify the bottleneck and the system's throughput is set.",
      body: `# Process analysis\n\nA process is a sequence of steps that transforms inputs into outputs. Every business is one. Operations management is the discipline of measuring, analyzing, and redesigning processes so they deliver the right quality at the right cost in the right time.\n\n## Core metrics\n\n- **Throughput** — units processed per unit time (orders per hour, patients per day).\n- **Cycle time** — time between successive completions.\n- **Flow time (lead time)** — time a single unit spends in the system from entry to exit.\n- **Work-in-process (WIP) / inventory** — units inside the system at any moment.\n- **Capacity** — the maximum sustainable throughput.\n- **Utilization** — actual throughput / capacity.\n\n## Little's Law\n\nThe single most important equation in operations:\n\n\`Inventory = Throughput × Flow time\`\n\n*I = T × FT.* Holds for any stable process — manufacturing, services, software pipelines, hospital ERs.\n\nWorked example: a coffee shop serves 50 customers/hour, and each customer spends 6 minutes in the store. Average inventory of customers = 50/hr × 0.1 hr = **5 customers** in the shop on average. If the queue is consistently longer, either throughput is lower than claimed or flow time is longer than claimed.\n\n## The bottleneck\n\nIn any process with sequential steps of unequal capacity, the *slowest* step sets the throughput of the whole system. Eli Goldratt's *Theory of Constraints* hammered this: improving a non-bottleneck step doesn't help. The five-step TOC playbook:\n\n1. **Identify** the constraint.\n2. **Exploit** it — squeeze every drop out (no idle time, perfect quality input).\n3. **Subordinate** everything else to the constraint.\n4. **Elevate** the constraint (add capacity).\n5. **Repeat** — once the old bottleneck is broken, a new one emerges.\n\n## Utilization vs queue\n\nQueueing theory shows wait time explodes nonlinearly as utilization approaches 100%. Run a process at 95% utilization and tiny variability produces huge queues. This is why hospitals with 95% bed utilization have ER waits measured in hours, and why software teams with everyone "fully booked" deliver less than teams that leave 20% slack. Operations design *for* slack at the bottleneck.\n\n## Process design choices\n\n- **Make-to-stock vs make-to-order** — finished-goods inventory vs lead time.\n- **Push vs pull** — schedule by forecast (push) or by downstream demand signal (pull). Toyota's kanban is the canonical pull system.\n- **Batch vs flow** — large batches amortize setup cost but create lumpy WIP; small batches smooth flow but require fast changeovers.\n- **Centralized vs distributed** — one big plant vs many small ones; cost-of-scale vs cost-of-distance trade-off.`,
      videos: [
        { title: "Operations Management Foundations", source: "LinkedIn Learning", url: "https://www.linkedin.com/learning/search?keywords=operations%20management%20foundations" }, 
        { title: "Little's Law — Operations Management", source: "YouTube — MIT OCW", url: "https://www.youtube.com/watch?v=NyKbVo0OkLA" },
        { title: "Theory of Constraints — Goldratt", source: "YouTube — Goldratt Institute", url: "https://www.youtube.com/watch?v=K3Lt2L2eVbI" },
      ],
      readings: [
        { title: "The Power of Process", source: "Harvard Business Review", url: "https://hbr.org/2011/02/the-power-of-process" },
        { title: "Decoding the DNA of the Toyota Production System", source: "Harvard Business Review", url: "https://hbr.org/1999/09/decoding-the-dna-of-the-toyota-production-system" },
      ],
    },
    {
      id: "l2",
      title: "Inventory management",
      summary: "Inventory is frozen cash. EOQ and safety stock are the foundations of how much, when, and why.",
      body: `# Inventory management\n\nInventory is cash converted into stuff. Too little and you stock out and lose sales; too much and you tie up working capital, fill warehouses, and risk obsolescence. The discipline is balancing those costs.\n\n## Why hold inventory\n\n- **Cycle stock** — to bridge between orders.\n- **Safety stock** — buffer against demand and lead-time variability.\n- **Pipeline (in-transit) stock** — material moving through the supply chain.\n- **Seasonal stock** — pre-built ahead of demand peaks.\n- **Speculative stock** — held against expected price rises (common in commodities).\n\nEach has different drivers and different remedies.\n\n## Economic order quantity (EOQ)\n\nThe classic formula (Ford Whitman Harris, 1913) balances ordering cost against holding cost:\n\n\`EOQ = √(2 × D × S / H)\`\n\nwhere D = annual demand, S = cost per order (placement, setup, freight), H = holding cost per unit per year (capital, storage, shrinkage).\n\nWorked example: D = 10,000 units, S = $50, H = $4. EOQ = √(2 × 10,000 × 50 / 4) = √250,000 = **500 units per order.** That implies 20 orders per year and average inventory of 250 units.\n\nEOQ is robust — total cost is flat near the optimum, so being off by 30% barely matters. The real value is *direction*: when ordering costs fall (electronic procurement, automation), order more often in smaller batches. When holding costs rise (capital expensive, shelf life short), do the same.\n\n## Safety stock\n\n\`Safety stock = z × σ_LT\`\n\nwhere z is the service-level multiplier (z ≈ 1.65 for 95%, 2.33 for 99%) and σ_LT is the standard deviation of demand over the lead time.\n\nThe punchline: 99% service requires roughly *3× the safety stock* of 90% service. The last percentage points of service are extraordinarily expensive. Stratify SKUs by criticality (ABC analysis) and apply different service levels accordingly.\n\n## Bullwhip effect\n\nForrester (1958) and Lee, Padmanabhan, Whang (1997) documented that small demand fluctuations at the consumer end amplify dramatically as you move upstream — retailer to distributor to manufacturer to component supplier. Causes: demand forecasting based on orders rather than POS data, batch ordering, price promotions, rationing games. Solutions: share point-of-sale data with suppliers (VMI — vendor-managed inventory), reduce lot sizes, smooth pricing.\n\n## Just-in-time and its limits\n\nJIT minimizes inventory by tight coupling with suppliers and frequent small deliveries. Hugely improved capital efficiency for decades — until COVID-19 and the chip shortage reminded everyone that lean supply chains are *fragile* supply chains. The post-2020 shift to "just-in-case" buffers is a recalibration, not a rejection.`,
      videos: [
        { title: "Operations Management Foundations", source: "LinkedIn Learning", url: "https://www.linkedin.com/learning/search?keywords=operations%20management%20foundations" }, 
        { title: "Inventory Management — EOQ", source: "YouTube — Operations Management 101", url: "https://www.youtube.com/watch?v=KMqlqVnYukM" },
        { title: "The Bullwhip Effect", source: "YouTube — MIT Sloan", url: "https://www.youtube.com/watch?v=AjUdZcRBhgw" },
      ],
      readings: [
        { title: "The Bullwhip Effect in Supply Chains", source: "Harvard Business Review", url: "https://hbr.org/1997/04/the-bullwhip-effect-in-supply-chains" },
        { title: "From Superstorms to Factory Fires: Managing Disruptions", source: "Harvard Business Review", url: "https://hbr.org/2014/01/from-superstorms-to-factory-fires-managing-unpredictable-supply-chain-disruptions" },
      ],
    },
    {
      id: "l3",
      title: "Lean and quality",
      summary: "Toyota's manufacturing philosophy turned operations into a competitive weapon — and reshaped every industry it touched.",
      body: `# Lean and quality\n\nLean grew out of the Toyota Production System (TPS), developed at Toyota by Taiichi Ohno and Eiji Toyoda between the 1950s and 1980s, and codified for Western audiences by Womack, Jones, and Roos in *The Machine That Changed the World* (1990).\n\n## The two pillars of TPS\n\n1. **Just-in-time** — produce what the next step needs, when it needs it, in the quantity it needs. Pull, not push.\n2. **Jidoka (autonomation)** — build quality in at the source. Any worker (and any machine) can stop the line on detecting a defect, surfacing problems instantly rather than burying them in WIP.\n\nUnderneath both: *eliminate waste (muda)*. The seven (now eight) wastes:\n\n- Overproduction\n- Waiting\n- Transportation\n- Over-processing\n- Inventory\n- Motion\n- Defects\n- Underutilized talent (added later)\n\n## The Toyota cultural piece\n\nWestern adopters often copy the tools (kanban cards, andon cords, 5S workplace organization) without the culture — *kaizen* (continuous improvement by everyone, every day), *genchi genbutsu* (go to the source — managers walk the floor), respect for people, long-term thinking. The tools without the culture rarely deliver.\n\n## Six Sigma\n\nDeveloped at Motorola in the 1980s and made famous by Jack Welch at GE. Where lean focuses on speed and waste, **Six Sigma focuses on variation**. Aim: process defects below 3.4 per million opportunities. Uses the DMAIC cycle:\n\n1. **Define** — the problem and customer requirement.\n2. **Measure** — current performance.\n3. **Analyze** — root causes (Pareto, fishbone, regression).\n4. **Improve** — pilot a change.\n5. **Control** — institutionalize the gain (SPC charts, standard work).\n\nMany large firms run *Lean Six Sigma* — combining waste reduction with variation reduction.\n\n## Statistical process control (SPC)\n\nWalter Shewhart's contribution. Plot output measurements over time with control limits at ±3 standard deviations from the mean. Common-cause variation (random noise within limits) is left alone; special-cause variation (a point outside limits, a run on one side of the mean) is investigated. The crucial distinction: do not "react" to common-cause variation — chasing noise makes processes worse.\n\n## Quality is free\n\nPhilip Crosby's title and central claim: the cost of *preventing* defects is far less than the cost of *finding and fixing* them after the fact (rework, scrap, warranty, lost customers, brand damage). For most manufacturing operations the **cost of poor quality** runs 15-25% of revenue.\n\n## Applicability beyond manufacturing\n\nThe biggest lean transformations of the past 25 years have been in services — hospitals (Virginia Mason), software (DevOps, Kanban for engineering), startups (Eric Ries's *The Lean Startup* applies the build-measure-learn loop to product-market fit). The underlying ideas — pull, small batches, surface problems immediately, continuous improvement — generalize.`,
      videos: [
        { title: "Operations Management Foundations", source: "LinkedIn Learning", url: "https://www.linkedin.com/learning/search?keywords=operations%20management%20foundations" }, 
        { title: "Lean Manufacturing — Toyota Production System", source: "YouTube — Toyota", url: "https://www.youtube.com/watch?v=v8KrL4uy4Mo" },
        { title: "Six Sigma DMAIC Explained", source: "YouTube — GoLeanSixSigma", url: "https://www.youtube.com/watch?v=FRJzdUscqsw" },
      ],
      readings: [
        { title: "Decoding the DNA of the Toyota Production System", source: "Harvard Business Review", url: "https://hbr.org/1999/09/decoding-the-dna-of-the-toyota-production-system" },
        { title: "The Contradictions That Drive Toyota's Success", source: "Harvard Business Review", url: "https://hbr.org/2008/06/the-contradictions-that-drive-toyotas-success" },
      ],
    },
  ],
  quiz: [
    { id: "q1", prompt: "If a process has throughput of 50/hr and flow time of 2 hours, average inventory is:", choices: ["25", "50", "100", "200"], answerIndex: 2, explanation: "Little's Law: I = T × FT = 50 × 2 = 100." },
    { id: "q2", prompt: "Annual demand 10,000; order cost $50; holding cost $4/unit/year. EOQ:", choices: ["250", "500", "1,000", "2,000"], answerIndex: 1, explanation: "sqrt(2×10000×50/4) = sqrt(250000) = 500." },
    { id: "q3", prompt: "In the Theory of Constraints, improving a non-bottleneck step:", choices: ["Increases throughput proportionally", "Has no effect on throughput", "Decreases throughput", "Always reduces cost"], answerIndex: 1, explanation: "System throughput is set by the bottleneck." },
  ],
  assignment: {
    id: "a1",
    title: "Process redesign",
    prompt: "Map a real process you've experienced (a coffee order, an ER visit, a software deploy, an expense report). Identify the bottleneck, estimate throughput and flow time, and propose two specific redesigns. For each, predict the effect on throughput, flow time, and total cost.",
    rubric: "Accurate process map (3 pts). Bottleneck correctly identified (2 pts). Two concrete redesigns (3 pts). Quantitative impact estimate (2 pts).",
  },
};