/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedCapstoneRouteImport } from './routes/_authenticated/capstone'
import { Route as AuthenticatedWeekWeekRouteImport } from './routes/_authenticated/week.$week'
import { Route as AuthenticatedQuizWeekRouteImport } from './routes/_authenticated/quiz.$week'
import { Route as AuthenticatedLessonWeekLessonRouteImport } from './routes/_authenticated/lesson.$week.$lesson'
import { Route as AuthenticatedAssignmentWeekIdRouteImport } from './routes/_authenticated/assignment.$week.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/_authenticated/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/_authenticated/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCapstoneRoute = AuthenticatedCapstoneRouteImport.update({
  id: '/_authenticated/capstone',
  path: '/capstone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeekWeekRoute = AuthenticatedWeekWeekRouteImport.update({
  id: '/_authenticated/week/$week',
  path: '/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizWeekRoute = AuthenticatedQuizWeekRouteImport.update({
  id: '/_authenticated/quiz/$week',
  path: '/quiz/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonWeekLessonRoute =
  AuthenticatedLessonWeekLessonRouteImport.update({
    id: '/_authenticated/lesson/$week/$lesson',
    path: '/lesson/$week/$lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAssignmentWeekIdRoute =
  AuthenticatedAssignmentWeekIdRouteImport.update({
    id: '/_authenticated/assignment/$week/$id',
    path: '/assignment/$week/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capstone': typeof AuthenticatedCapstoneRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/quiz/$week': typeof AuthenticatedQuizWeekRoute
  '/week/$week': typeof AuthenticatedWeekWeekRoute
  '/assignment/$week/$id': typeof AuthenticatedAssignmentWeekIdRoute
  '/lesson/$week/$lesson': typeof AuthenticatedLessonWeekLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capstone': typeof AuthenticatedCapstoneRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/quiz/$week': typeof AuthenticatedQuizWeekRoute
  '/week/$week': typeof AuthenticatedWeekWeekRoute
  '/assignment/$week/$id': typeof AuthenticatedAssignmentWeekIdRoute
  '/lesson/$week/$lesson': typeof AuthenticatedLessonWeekLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/capstone': typeof AuthenticatedCapstoneRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/quiz/$week': typeof AuthenticatedQuizWeekRoute
  '/_authenticated/week/$week': typeof AuthenticatedWeekWeekRoute
  '/_authenticated/assignment/$week/$id': typeof AuthenticatedAssignmentWeekIdRoute
  '/_authenticated/lesson/$week/$lesson': typeof AuthenticatedLessonWeekLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capstone'
    | '/curriculum'
    | '/dashboard'
    | '/tutor'
    | '/api/chat'
    | '/quiz/$week'
    | '/week/$week'
    | '/assignment/$week/$id'
    | '/lesson/$week/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capstone'
    | '/curriculum'
    | '/dashboard'
    | '/tutor'
    | '/api/chat'
    | '/quiz/$week'
    | '/week/$week'
    | '/assignment/$week/$id'
    | '/lesson/$week/$lesson'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/capstone'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/tutor'
    | '/api/chat'
    | '/_authenticated/quiz/$week'
    | '/_authenticated/week/$week'
    | '/_authenticated/assignment/$week/$id'
    | '/_authenticated/lesson/$week/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedCapstoneRoute: typeof AuthenticatedCapstoneRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthenticatedQuizWeekRoute: typeof AuthenticatedQuizWeekRoute
  AuthenticatedWeekWeekRoute: typeof AuthenticatedWeekWeekRoute
  AuthenticatedAssignmentWeekIdRoute: typeof AuthenticatedAssignmentWeekIdRoute
  AuthenticatedLessonWeekLessonRoute: typeof AuthenticatedLessonWeekLessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capstone': {
      id: '/_authenticated/capstone'
      path: '/capstone'
      fullPath: '/capstone'
      preLoaderRoute: typeof AuthenticatedCapstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/week/$week': {
      id: '/_authenticated/week/$week'
      path: '/week/$week'
      fullPath: '/week/$week'
      preLoaderRoute: typeof AuthenticatedWeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/$week': {
      id: '/_authenticated/quiz/$week'
      path: '/quiz/$week'
      fullPath: '/quiz/$week'
      preLoaderRoute: typeof AuthenticatedQuizWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lesson/$week/$lesson': {
      id: '/_authenticated/lesson/$week/$lesson'
      path: '/lesson/$week/$lesson'
      fullPath: '/lesson/$week/$lesson'
      preLoaderRoute: typeof AuthenticatedLessonWeekLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignment/$week/$id': {
      id: '/_authenticated/assignment/$week/$id'
      path: '/assignment/$week/$id'
      fullPath: '/assignment/$week/$id'
      preLoaderRoute: typeof AuthenticatedAssignmentWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedCapstoneRoute: AuthenticatedCapstoneRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  ApiChatRoute: ApiChatRoute,
  AuthenticatedQuizWeekRoute: AuthenticatedQuizWeekRoute,
  AuthenticatedWeekWeekRoute: AuthenticatedWeekWeekRoute,
  AuthenticatedAssignmentWeekIdRoute: AuthenticatedAssignmentWeekIdRoute,
  AuthenticatedLessonWeekLessonRoute: AuthenticatedLessonWeekLessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
